USE [master]
GO

/****** Object:  Database [HotelAutomation]    Script Date: 19.01.2023 19:10:59 ******/
CREATE DATABASE [HotelAutomation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelAutomation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HotelAutomation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HotelAutomation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HotelAutomation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelAutomation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HotelAutomation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HotelAutomation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HotelAutomation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HotelAutomation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HotelAutomation] SET ARITHABORT OFF 
GO

ALTER DATABASE [HotelAutomation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HotelAutomation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HotelAutomation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HotelAutomation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HotelAutomation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HotelAutomation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HotelAutomation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HotelAutomation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HotelAutomation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HotelAutomation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HotelAutomation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HotelAutomation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HotelAutomation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HotelAutomation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HotelAutomation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HotelAutomation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HotelAutomation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HotelAutomation] SET RECOVERY FULL 
GO

ALTER DATABASE [HotelAutomation] SET  MULTI_USER 
GO

ALTER DATABASE [HotelAutomation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HotelAutomation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HotelAutomation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HotelAutomation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HotelAutomation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HotelAutomation] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HotelAutomation] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HotelAutomation] SET  READ_WRITE 
GO


